In [18]:
import pandas as pd

In [19]:
df = pd.read_csv(
    "подбор_комбинаций.csv",
    sep=",",        # разделитель
    encoding="utf-8",
    decimal=".",    # если числа с точкой
)

In [20]:
df.head()      # первые строки
df.info()      # типы данных
df.describe()  # статистика

<class 'pandas.DataFrame'>
RangeIndex: 30184 entries, 0 to 30183
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             30184 non-null  int64
 1   total_error_pct  30184 non-null  float64
 2   d1_отн           30184 non-null  float64
 3   c_а1_отн         30184 non-null  float64
 4   с_а_отн          30184 non-null  float64
 5   Hт_ср_отн        30184 non-null  float64
 6   H_т1             30184 non-null  float64
 7   π_к_полн         30184 non-null  float64
 8   η_к_полн         30184 non-null  float64
 9   err_π_к_pct      30184 non-null  float64
 10  err_η_к_pct      30184 non-null  float64
dtypes: float64(10), int64(1)
memory usage: 2.5 MB

,rank,total_error_pct,d1_отн,c_а1_отн,с_а_отн,Hт_ср_отн,H_т1,π_к_полн,η_к_полн,err_π_к_pct,err_η_к_pct
count,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000,30184.000000
mean,15092.500000,167.270875,0.450000,0.550000,0.425000,0.250000,0.200000,39.328226,0.794933,157.308642,9.962232
std,8713.514599,251.159654,0.100002,0.100002,0.114566,0.100002,0.031623,49.332101,0.030322,249.402075,3.434389
min,1.000000,6.367971,0.300000,0.400000,0.250000,0.100000,0.150000,3.554401,0.684835,0.002522,4.166894
25%,7546.750000,39.895755,0.350000,0.450000,0.337500,0.150000,0.170000,10.346858,0.776162,31.459852,7.291378
50%,15092.500000,60.851519,0.450000,0.550000,0.425000,0.250000,0.200000,17.714303,0.800225,52.808458,9.362802
75%,22638.250000,139.495632,0.550000,0.650000,0.512500,0.350000,0.230000,41.592433,0.818514,128.529853,12.088335
max,30184.000000,1146.767581,0.600000,0.700000,0.600000,0.400000,0.250000,224.325047,0.846099,1132.555202,22.432470

In [21]:
df_sorted = df.sort_values("err_η_к_pct", ascending=True)

In [22]:
filtered_sorted = df[
    (df["c_а1_отн"] > df["с_а_отн"])
    ].sort_values("err_η_к_pct", ascending=True)

In [23]:
filtered_sorted

,rank,total_error_pct,d1_отн,c_а1_отн,с_а_отн,Hт_ср_отн,H_т1,π_к_полн,η_к_полн,err_π_к_pct,err_η_к_pct
13781,13782,56.907990,0.30,0.5,0.45,0.4,0.25,8.601121,0.846099,52.741096,4.166894
13757,13758,56.844313,0.30,0.5,0.45,0.4,0.24,8.613227,0.846074,52.674578,4.169735
13734,13735,56.778223,0.30,0.5,0.45,0.4,0.23,8.625791,0.846048,52.605543,4.172680
13707,13708,56.709689,0.30,0.5,0.45,0.4,0.22,8.638819,0.846021,52.533960,4.175729
13682,13683,56.638678,0.30,0.5,0.45,0.4,0.21,8.652317,0.845993,52.459796,4.178883
...,...,...,...,...,...,...,...,...,...,...,...
29025,29026,929.340370,0.30,0.4,0.25,0.1,0.21,183.261447,0.685039,906.931030,22.409340
29081,29082,938.748525,0.35,0.4,0.25,0.1,0.19,184.973663,0.685036,916.338807,22.409718
29041,29042,932.208739,0.30,0.4,0.25,0.1,0.20,183.782132,0.684973,909.791934,22.416805
29060,29061,935.179795,0.30,0.4,0.25,0.1,0.19,184.321461,0.684905,912.755281,22.424514
29079,29080,938.255317,0.30,0.4,0.25,0.1,0.18,184.879758,0.684835,915.822847,22.432470